import type { App } from 'vue';
import {
  Button,
  Input,
  Tabs,
  Form,
  InputNumber,
  Select,
  Drawer,
  Collapse,
  Tooltip,
  Empty,
  ConfigProvider,
  Layout,
  Menu,
  Table,
  Pagination,
  Divider,
  Avatar,
  Dropdown,
  Popover,
  Modal,
  Checkbox,
  Slider,
  Col,
  Row,
  Carousel,
  Timeline,
  Switch,
} from 'ant-design-vue';

export const useAntDesign = (app: App) => {
  app.use(Button);
  app.use(Input);
  app.use(Tabs);
  app.use(Form);
  app.use(InputNumber);
  app.use(Select);
  app.use(Drawer);
  app.use(Collapse);
  app.use(Tooltip);
  app.use(Empty);
  app.use(ConfigProvider);
  app.use(Layout);
  app.use(Menu);
  app.use(Table);
  app.use(Pagination);
  app.use(Divider);
  app.use(Avatar);
  app.use(Dropdown);
  app.use(Popover);
  app.use(Modal);
  app.use(Checkbox);
  app.use(Slider);
  app.use(Col);
  app.use(Row);
  app.use(Carousel);
  app.use(Timeline);
  app.use(Switch);
};
